import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'lul - S2',
  description: 'Generated by NextJS, well you have to guess that.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <main className={inter.className}>{children}</main>
  )
}
